### ISSUE TITLE
Is there an implementation of modulo operation for filed?

### ISSUE THREAD

**Issue by wenti-123** [arkworks-rs/algebra#712] opened 2023-12-11 02:56 UTC
Hi, I am currently working on a project involving the arkworks library and have a question regarding modulo operation on field elements.

Specifically, I am interested in calculating the result of taking **a field element modulo an arbitrary number**. I've searched through the documentation but couldn't find a direct implementation or information regarding this operation.

Could you kindly provide guidance on whether arkworks supports modulo operation on field elements, and if so, how I can perform such operations?

Thank you in advance for your time and assistance. I appreciate your efforts in developing and maintaining the arkworks library.

**Comment by burdges** [comment] 2023-12-11 13:02
All elements are invertable in a field, so the remainer is always zero (or divide by zero error).

"Reduce" means the remainder in integer division.  It lives in https://github.com/arkworks-rs/algebra/blob/master/ff/src/fields/models/fp/montgomery_backend.rs. [ark-poly](https://docs.rs/ark-poly/latest/ark_poly) has polynomial division.

**Comment by mmaker** [comment] 2023-12-22 10:56
Agree with @burdges: for fields this doesn't make sense. 
For BigInt it could be useful, in which case it's a duplicate of #717 -- I think we can close it?

**Comment by Pratyush** [comment] 2023-12-26 18:07
Agreed that an element of a field only coincidentally happens to be an integer (and that only for prime fields). The recommended way to do what you're looking for is via #717

**Closed by Pratyush** 2023-12-26 18:07 UTC

**Comment by hdvanegasm** [comment] 2024-01-03 23:14
> Agree with @burdges: for fields this doesn't make sense, but for BigInt it could be useful! in which case though it's a duplicate of #717 -- I think we can close it?

I'm currently implementing this functionality to close https://github.com/arkworks-rs/algebra/issues/717.
