### ISSUE TITLE
Support Coset domain for univariate poly?

### ISSUE THREAD

**Issue by tsunrise** [arkworks-rs/algebra#298] opened 2021-06-25 23:33 UTC
Coset radix-2 domain can be useful in some circumstances. 

Perhaps we can add an `offset: F` to `Radix2EvaluationDomain`?
(Doing so, the domain will also be consistent with the domain in `r1cs-std`)

**Comment by Pratyush** [comment] 2021-07-16 00:22
I think this is a duplicate of https://github.com/arkworks-rs/algebra/issues/88

**Closed** 2021-07-16 00:22 UTC
