### ISSUE TITLE
`multi_miller_loop` panics on inputs with different length

### ISSUE THREAD

**Issue by gshep** [arkworks-rs/algebra#707] opened 2023-11-29 11:53 UTC
The following change (or vice versa)

```diff
diff --git a/test-templates/src/pairing.rs b/test-templates/src/pairing.rs
index 755ee22..82e9cdc 100644
--- a/test-templates/src/pairing.rs
+++ b/test-templates/src/pairing.rs
@@ -45,7 +45,7 @@ macro_rules! test_pairing {
                     let c = <$Pairing as Pairing>::G1::rand(rng).into_affine();
                     let d = <$Pairing as Pairing>::G2::rand(rng).into_affine();
                     let ans1 = <$Pairing>::pairing(a, b) + &<$Pairing>::pairing(c, d);
-                    let ans2 = <$Pairing>::multi_pairing(&[a, c], &[b, d]);
+                    let ans2 = <$Pairing>::multi_pairing(&[a], &[b, d]);
                     assert_eq!(ans1, ans2);
                 }
             }
```

leads to executable binary crash:
```shell
$ cargo test -p ark-test-curves -F bls12_381_curve bls12_381::tests::pairing::test_multi_pairing
...
running 1 test
test bls12_381::tests::pairing::test_multi_pairing ... FAILED

failures:

---- bls12_381::tests::pairing::test_multi_pairing stdout ----
thread 'bls12_381::tests::pairing::test_multi_pairing' panicked at 'itertools: .zip_eq() reached end of one iterator before the other', ~/.cargo/registry/src/index.crates.io-6f17d22bba15001f/itertools-0.12.0/src/zip_eq_impl.rs:50:17
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


failures:
    bls12_381::tests::pairing::test_multi_pairing

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 134 filtered out; finished in 0.02s

error: test failed, to rerun pass `-p ark-test-curves --lib`
```

**Comment by burdges** [comment] 2023-11-29 12:44
That's the only option with the current intereface,  It usually not problematic since protocols prepare their pairings directly.  And scripting langauges like EVM take pairs in (G1,G2).

In fact, there is a good reason for `MillerLoopOutput<P>` to be an enum, or else use `Option<MillerLoopOutput<P>>`:  You can detect points not being in the proper subgroup using the Miller loop, so then your deserialization avoids the expensive subgroup check, doing only the on-curve check.  Arkworks & others have never embraced this optimization because cofactors have caused so many nasty bugs, but you'd do this if you wanted a high performance verifiers.

**Comment by mmagician** [comment] 2024-01-11 08:26
It's specifically caused by [this zipping operation](https://github.com/arkworks-rs/algebra/blob/2977690b021f2b6bc291bbcfe65f3cb00bde7335/ec/src/models/bls12/mod.rs#L54).
Closing as it's expected behaviour as @burdges says.

**Closed by mmagician** 2024-01-11 08:26 UTC
